spring:
  config:
    use-legacy-processing: true
  profiles:
    active: local
    include:
      - flyway
      - mysql
      - security
jwt:
  secret: VlwEyVBsYt9V7zq57TejMnVUyzblYcfPQye08f7MGVA9XkHa